DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS chapters;

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  author TEXT NOT NULL
);

CREATE TABLE chapters (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  length INTEGER CHECK (length > 0),
  chapter_id BIGINT REFERENCES chapters(id)
)